email: your-email@domain.com

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

title: "Gabriel Cornish"
tagline: ""
description: "Follow <a href=\"https://micro.blog/GabrielCornish\">@GabrielCornish on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/GabrielCornish\">@GabrielCornish on Micro.blog</a>."
baseurl: ""
url: "http://www.gabrielcornish.com"
markdown: "kramdown"
username: "GabrielCornish"
microblog_user: "GabrielCornish"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Gabriel Cornish"
name: "Gabriel Cornish"
gravatar_hash: "4b96e336b723f436b553294d690eba39"
avatar: "https://micro.blog/GabrielCornish/avatar.jpg"
full_name: "Gabriel Cornish"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "3669"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"